/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "white": "var(--color-surface-container-lowest)",
        "slate": {
          "100": "var(--color-surface-container)",
          "200": "var(--color-surface-container-high)",
          "300": "var(--color-surface-variant)",
          "400": "var(--color-outline-variant)",
          "500": "var(--color-outline)",
          "600": "var(--color-on-surface-variant)",
          "700": "var(--color-on-surface-variant)",
          "800": "var(--color-on-surface)",
          "900": "var(--color-on-surface)"
        },
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-surface": "var(--color-on-surface)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-tertiary": "var(--color-on-tertiary)",
        "error-container": "var(--color-error-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-error": "var(--color-on-error)",
        "primary-container": "var(--color-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-variant": "var(--color-surface-variant)",
        "outline-variant": "var(--color-outline-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "secondary": "var(--color-secondary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "outline": "var(--color-outline)",
        "error": "var(--color-error)",
        "on-secondary": "var(--color-on-secondary)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "primary": "var(--color-primary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface": "var(--color-surface)",
        "on-primary-container": "var(--color-on-primary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-primary": "var(--color-on-primary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container": "var(--color-surface-container)",
        "surface-tint": "var(--color-surface-tint)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-background": "var(--color-on-background)",
        "surface-dim": "var(--color-surface-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary": "var(--color-tertiary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "background": "var(--color-background)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "tertiary-fixed": "var(--color-tertiary-fixed)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "sm": "8px",
        "gutter": "16px",
        "xs": "4px",
        "xl": "32px",
        "base": "8px",
        "sidebar_width": "240px",
        "lg": "24px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "data-tabular": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
