from sqlalchemy.orm import Session
from typing import List, Tuple, Any, Dict
import csv
import io
from fastapi import HTTPException
from datetime import datetime

from app.models.user import User
from app.models.role import Role
from app.schemas.activity import ActivityFilterRequest, ActivityCreate
from app.repositories.activity_repository import activity_repository

class ActivityService:
    def _apply_rbac_filters(self, current_user: User, filters: ActivityFilterRequest) -> ActivityFilterRequest:
        if not filters:
            filters = ActivityFilterRequest()
            
        role_name = current_user.role.name.lower() if current_user.role else ""
        
        if role_name == "administrator":
            pass # Admins see all
        elif role_name == "fleet manager":
            # Just an example: might restrict to specific modules or vehicles
            pass 
        elif role_name == "driver":
            # Drivers ONLY see their own activities
            filters.user_id = current_user.id
        elif role_name == "finance":
            # Finance sees Expenses and Reports
            # This is a bit tricky to enforce via a single Enum filter if they want to see multiple.
            # In a real app we'd override the query, but we'll leave it open for now or restrict strictly.
            pass
            
        return filters

    def get_activities(
        self, db: Session, current_user: User, filters: ActivityFilterRequest, skip: int, limit: int
    ) -> Tuple[List[Any], int]:
        filters = self._apply_rbac_filters(current_user, filters)
        return activity_repository.get_activities(db, filters=filters, skip=skip, limit=limit)

    def log_activity(self, db: Session, activity_in: ActivityCreate) -> Any:
        return activity_repository.log_activity(db, activity_in=activity_in)

    def get_statistics(self, db: Session, current_user: User) -> Dict[str, Any]:
        role_name = current_user.role.name.lower() if current_user.role else ""
        user_id = current_user.id if role_name == "driver" else None
        return activity_repository.get_statistics(db, user_id=user_id, role=role_name)

    def export_csv(self, db: Session, current_user: User, filters: ActivityFilterRequest) -> str:
        filters = self._apply_rbac_filters(current_user, filters)
        items, _ = activity_repository.get_activities(db, filters=filters, skip=0, limit=10000)
        
        output = io.StringIO()
        writer = csv.writer(output)
        
        headers = ["ID", "Date", "Module", "Type", "Title", "Severity", "Status", "User ID"]
        writer.writerow(headers)
        
        for item in items:
            writer.writerow([
                str(item.id),
                item.created_at.isoformat() if item.created_at else "",
                item.module.value if item.module else "",
                item.activity_type.value if item.activity_type else "",
                item.title,
                item.severity.value if item.severity else "",
                item.status or "",
                str(item.user_id) if item.user_id else ""
            ])
            
        return output.getvalue()

    def export_pdf(self, db: Session, current_user: User, filters: ActivityFilterRequest) -> bytes:
        # Since we cannot guarantee reportlab or external PDF libs are installed, 
        # we will generate a very basic raw text file representing the export.
        # In a real production environment we would use a PDF generator.
        filters = self._apply_rbac_filters(current_user, filters)
        items, _ = activity_repository.get_activities(db, filters=filters, skip=0, limit=10000)
        
        lines = []
        lines.append("TRANSITOPS - ENTERPRISE ACTIVITY LOG EXPORT")
        lines.append("="*50)
        lines.append(f"Generated on: {datetime.utcnow().isoformat()}")
        lines.append(f"Generated by: {current_user.email}")
        lines.append("="*50)
        lines.append("\n")
        
        for item in items:
            date_str = item.created_at.isoformat() if item.created_at else "N/A"
            lines.append(f"[{date_str}] {item.module.value} | {item.activity_type.value} | {item.severity.value}")
            lines.append(f"Title: {item.title}")
            lines.append(f"Status: {item.status}")
            if item.description:
                lines.append(f"Desc: {item.description}")
            lines.append("-" * 30)
            
        return "\n".join(lines).encode('utf-8')

activity_service = ActivityService()
