"""add_activity_log

Revision ID: 12c986e3b5bd
Revises: b933fe5721cc
Create Date: 2026-07-14 14:50:06.066363+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '12c986e3b5bd'
down_revision = 'b933fe5721cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_id', sa.UUID(), nullable=True),
    sa.Column('fuel_id', sa.UUID(), nullable=True),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('module', sa.Enum('AUTHENTICATION', 'DASHBOARD', 'VEHICLE', 'DRIVER', 'TRIP', 'MAINTENANCE', 'FUEL', 'EXPENSE', 'REPORTS', 'SETTINGS', 'NOTIFICATION', 'HELP_CENTER', 'QUICK_ACTIONS', 'CUSTOM_REPORTS', name='moduleenum'), nullable=False),
    sa.Column('activity_type', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'APPROVED', 'REJECTED', 'ASSIGNED', 'COMPLETED', 'CANCELLED', 'EXPORTED', 'LOGIN', 'LOGOUT', 'PASSWORD_RESET', 'NOTIFICATION', 'SYSTEM', name='activitytypeenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuel_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
