"""add_help_center

Revision ID: 0d0ab55c0d72
Revises: 27b8b6d1d59b
Create Date: 2026-07-13 10:50:26.017543+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0ab55c0d72'
down_revision = '27b8b6d1d59b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['help_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_articles_id'), 'help_articles', ['id'], unique=False)
    op.create_index(op.f('ix_help_articles_slug'), 'help_articles', ['slug'], unique=True)
    op.alter_column('drivers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('drivers', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('drivers', 'safety_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('drivers', 'total_trips',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('drivers', 'joined_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('drivers', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('drivers', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_drivers_license_number', table_name='drivers')
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.drop_index('ix_drivers_user_id', table_name='drivers')
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=True)
    op.alter_column('expenses', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('expenses', 'vehicle_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('expenses', 'trip_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('expenses', 'maintenance_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('expenses', 'approved_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('expenses', 'recorded_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('expenses', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('fuel_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'vehicle_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'trip_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('fuel_logs', 'refuel_date',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('fuel_logs', 'recorded_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('fuel_logs', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('fuel_logs', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'vehicle_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('maintenance_logs', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_maintenance_logs_maintenance_number', table_name='maintenance_logs')
    op.create_index(op.f('ix_maintenance_logs_maintenance_number'), 'maintenance_logs', ['maintenance_number'], unique=True)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trips', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trips', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('trips', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trips', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_trips_trip_number', table_name='trips')
    op.create_index(op.f('ix_trips_trip_number'), 'trips', ['trip_number'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vehicles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('vehicles', 'current_odometer_km',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vehicles', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vehicles', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_vehicles_registration_number', table_name='vehicles')
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.create_index('ix_vehicles_registration_number', 'vehicles', ['registration_number'], unique=False)
    op.alter_column('vehicles', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('vehicles', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Available'"),
               existing_nullable=False)
    op.alter_column('vehicles', 'current_odometer_km',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('vehicles', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.drop_index(op.f('ix_trips_trip_number'), table_name='trips')
    op.create_index('ix_trips_trip_number', 'trips', ['trip_number'], unique=False)
    op.alter_column('trips', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('trips', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('trips', 'created_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Draft'"),
               existing_nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('trips', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.drop_index(op.f('ix_maintenance_logs_maintenance_number'), table_name='maintenance_logs')
    op.create_index('ix_maintenance_logs_maintenance_number', 'maintenance_logs', ['maintenance_number'], unique=False)
    op.alter_column('maintenance_logs', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'created_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('maintenance_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Pending'"),
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Medium'"),
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'vehicle_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('maintenance_logs', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'recorded_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('fuel_logs', 'refuel_date',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'trip_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('fuel_logs', 'vehicle_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('fuel_logs', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('expenses', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('expenses', 'recorded_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('expenses', 'approved_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('expenses', 'maintenance_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('expenses', 'trip_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('expenses', 'vehicle_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('expenses', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.create_index('ix_drivers_user_id', 'drivers', ['user_id'], unique=False)
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.create_index('ix_drivers_license_number', 'drivers', ['license_number'], unique=False)
    op.alter_column('drivers', 'updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('drivers', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('drivers', 'joined_date',
               existing_type=sa.DATE(),
               server_default=sa.text('(CURRENT_DATE)'),
               existing_nullable=False)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Available'"),
               existing_nullable=False)
    op.alter_column('drivers', 'total_trips',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('drivers', 'safety_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text("'100.00'"),
               existing_nullable=False)
    op.alter_column('drivers', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('drivers', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_help_articles_slug'), table_name='help_articles')
    op.drop_index(op.f('ix_help_articles_id'), table_name='help_articles')
    op.drop_table('help_articles')
    # ### end Alembic commands ###
