"""enhance_notifications

Revision ID: ae049a58d200
Revises: 12c986e3b5bd
Create Date: 2026-07-15 16:24:00.232457+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae049a58d200'
down_revision = '12c986e3b5bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('module_name', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('severity', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('icon_name', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('route', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('related_entity_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_notifications_related_entity_id'), 'notifications', ['related_entity_id'], unique=False)
    op.drop_column('notifications', 'icon')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'action_url')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('action_url', sa.VARCHAR(length=255), nullable=True))
    op.add_column('notifications', sa.Column('message', sa.TEXT(), nullable=False))
    op.add_column('notifications', sa.Column('icon', sa.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_notifications_related_entity_id'), table_name='notifications')
    op.drop_column('notifications', 'related_entity_id')
    op.drop_column('notifications', 'route')
    op.drop_column('notifications', 'icon_name')
    op.drop_column('notifications', 'severity')
    op.drop_column('notifications', 'module_name')
    op.drop_column('notifications', 'description')
    pass
    # ### end Alembic commands ###
